version: '2'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      # tehat a mysql workbench-ben a 3305-os port-on.. user és password az itteni
      # docker-compose down -v -t futtattam, miutan valtoztattam a fenti jelszot... (-v Remove named volumes declared in the `volumes`)
      # ez utan docker-compose up
      - '3305:3306'
    expose:
    # Opens port 3306 on the container
      - '3306'
  blog:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/blog
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: user
      DB_NAME: blog
      DB_PASSWORD: password
      DB_HOST: db
    